spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 180.76.184.26:8848
  application:
    name: common-service
ribbon:
  eager-load:
    #开启饿汉模式,第一次请求会快一点
    enabled: true
#logging:
#  level:
#    com.alibaba.customer.remote: debug
#feign:
#  ###想要设置feignClient的fallback指定容错类需要开启hystrix不然不管用，因为Feign的容错是hystrix
#  hystrix:
#    enabled: true
#  httpclient:
#    enabled: true
#    #连接池最大连接数
#    max-connections: 1000
#    #同一个连接支持的最大连接数
#    max-connections-per-route: 100
#  client:
#    config:
#      provider:
#        connectTimeout : 1500
#        loggerLevel: BASIC
##开启监控信息配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
---
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        #所属集群名称
        cluster-name: NJ
server:
  port: 9400
---
spring:
  profiles: prod
  cloud:
    nacos:
      discovery:
        #所属集群名称
        cluster-name: BJ
server:
  port: 9401
